name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  Publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Simulate dist
        run: |
          mkdir ./packages/generator/dist
          touch ./packages/generator/dist/bin.js

      - name: Install dependencies
        run: pnpm i

      - name: Publish 🚀
        working-directory: ./packages/generator
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
