# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Publish:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/generator

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4'
          registry-url: https://registry.npmjs.org
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install deps
        run: yarn install
      
      - name: Build 📦
        run: yarn build
      
      - name: Publish 🚀
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
